services:
  - type: web
    name: snapshot-api
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    buildFilter:
      paths:
        - Dockerfile
        - SnapshotWebApi/*
        - SnapshotLib/*
 #   envVars:
 #     - key: GITHUB_TOKEN
 #       sync: false  # Set this in the dashboard for security
